# Generated by Django 6.0.4 on 2026-04-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invitecode_studentapplication_delete_tutorinvite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
